language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  allow_failures:
    - php: 7.2

install:
  - composer selfupdate
  - composer install

script:
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpunit --testdox